require 'rake/tasklib'
require 'rexml/document'
include REXML

CONFIGURATION = ENV["CONFIGURATION"]||"Release"
PROJECT =ENV["PROJECT"]||"NQUnit"
ASSEMBLYNAME = ENV["ASSEMBLYNAME"]||"NQUnit"
SPEC = "..\\#{PROJECT}\\#{PROJECT}.nuspec"

PACKAGES = "..\\#{PROJECT}\\packages.config"
REPO = ENV["REPO"]||ASSEMBLYNAME

task :default => "build:build_package"
 
namespace :build do
  
  task :all => [:clean, :compile, :config, :test]
  task :build_package => [:increment_version, :add_dependencies, :copy_output, :nupack]
  
  desc "Increments patch number"
  task :increment_version do    
    doc =  Document.new(File.new SPEC)
    version_element = doc.elements['package/metadata/version']
    
    build_number = ENV["BUILD_NUMBER"].dup || increment_version(version_element)
        
    version_element.text = build_number
    File.open(SPEC,"w"){ |f| doc.write(f, 2) }
  end
  
  def increment_version(version_element)
    major,minor,patch = version_element.text.split "."
    patch = patch.to_i+1
    build_number = "#{major}.#{minor}.#{patch}"
  end
     
  desc "Adds dependencies from packages.config to nuspec"
  task :add_dependencies do
    doc = Document.new(File.new SPEC)
    dependencies = doc.elements['package/metadata/dependencies']
    dependencies.elements.delete_all 'dependency'
        
    Document.new(File.new PACKAGES).elements['packages'].each do |p|
        if(p.class == Element)
            #puts p.text
            puts p.attributes
            dependencies.add_element "dependency", {"id"=>p.attributes["id"],"version"=>p.attributes["version"]}
        end
    end
    
    File.open(SPEC,"w"){ |f| doc.write(f, 2) }
  end
  
  desc "Copy output files (dlls, pdbs) to output dir"
  task :copy_output do
    TARGET = "#{REPO}\\lib\\NET40"
    puts cp "..\\#{PROJECT}\\bin\\Release\\#{ASSEMBLYNAME}.dll", TARGET+"\\#{ASSEMBLYNAME}.dll"
    puts cp "..\\#{PROJECT}\\bin\\Release\\#{ASSEMBLYNAME}.pdb", TARGET+"\\#{ASSEMBLYNAME}.pdb"
  end
  
  desc "Tell nuget to pack this spec"
  task :nupack do
    #nuget pack ..\#{PROJECT}\#{PROJECT}.nuspec -o ..\Output\#{ASSEMBLYNAME}\ -BasePath ..\Output\#{ASSEMBLYNAME}
    sh "nuget pack #{SPEC} -o #{REPO} -BasePath #{REPO}"
  end  
end

